// Move country options to a separate file or keep here if small
export const countryOptions: readonly { value: string; name: string }[] = [
    { value: "US", name: "United States" },
    { value: "JP", name: "Japan" },
    { value: "IT", name: "Italy" },
    { value: "DE", name: "Germany" },
    { value: "FR", name: "France" },
    { value: "RU", name: "Russian Federation" },
    { value: "AT", name: "Austria" },
    { value: "NO", name: "Norway" },
    { value: "CZ", name: "Czech Republic" },
    { value: "KR", name: "Korea, Republic Of" },
    { value: "CH", name: "Switzerland" },
    { value: "TW", name: "Taiwan" },
    { value: "GB", name: "United Kingdom" },
    { value: "CA", name: "Canada" },
    { value: "ES", name: "Spain" },
    { value: "PL", name: "Poland" },
    { value: "SE", name: "Sweden" },
    { value: "RO", name: "Romania" },
    { value: "NL", name: "Netherlands" },
    { value: "BG", name: "Bulgaria" },
    { value: "VN", name: "Vietnam" },
    { value: "DK", name: "Denmark" },
    { value: "BE", name: "Belgium" },
    { value: "RS", name: "Serbia" },
    { value: "HU", name: "Hungary" },
    { value: "FI", name: "Finland" },
    { value: "IN", name: "India" },
    { value: "BR", name: "Brazil" },
    { value: "ZA", name: "South Africa" },
    { value: "GR", name: "Greece" },
    { value: "UA", name: "Ukraine" },
    { value: "SK", name: "Slovakia" },
    { value: "MX", name: "Mexico" },
    { value: "BA", name: "Bosnia And Herzegovina" },
    { value: "TR", name: "Turkey" },
    { value: "IE", name: "Ireland" },
    { value: "ID", name: "Indonesia" },
    { value: "IR", name: "Iran" },
    { value: "TH", name: "Thailand" },
    { value: "IL", name: "Israel" },
    { value: "HK", name: "Hong Kong" },
    { value: "CL", name: "Chile" },
    { value: "AR", name: "Argentina" },
    { value: "LT", name: "Lithuania" },
    { value: "MD", name: "Moldova" },
    { value: "SY", name: "Syria" },
    { value: "EE", name: "Estonia" },
    { value: "EC", name: "Ecuador" },
    { value: "NZ", name: "New Zealand" },
    { value: "MY", name: "Malaysia" },
    { value: "AU", name: "Australia" },
    { value: "SI", name: "Slovenia" },
    { value: "BY", name: "Belarus" },
    { value: "CN", name: "China" },
    { value: "ME", name: "Montenegro" },
    { value: "CO", name: "Colombia" },
    { value: "NG", name: "Nigeria" },
    { value: "KZ", name: "Kazakhstan" },
    { value: "FO", name: "Faroe Islands" },
    { value: "PT", name: "Portugal" },
    { value: "AM", name: "Armenia" },
    { value: "HN", name: "Honduras" },
    { value: "PE", name: "Peru" },
    { value: "NI", name: "Nicaragua" },
    { value: "LU", name: "Luxembourg" },
    { value: "CY", name: "Cyprus" },
    { value: "AO", name: "Angola" },
    { value: "PA", name: "Panama" },
    { value: "GU", name: "Guam" },
    { value: "LB", name: "Lebanon" },
    { value: "NC", name: "New Caledonia" },
    { value: "IS", name: "Iceland" },
    { value: "GE", name: "Georgia" },
    { value: "LV", name: "Latvia" },
    { value: "MT", name: "Malta" },
    { value: "PH", name: "Philippines" },
    { value: "TZ", name: "Tanzania" },
    { value: "LA", name: "Laos" },
    { value: "TN", name: "Tunisia" },
];

export const modelOptions: readonly { value: string; label: string }[] = [
    { value: "yolo11n.pt", label: "Nano (Fastest)" },
    { value: "yolo11s.pt", label: "Small (Balanced)" },
    { value: "yolo11m.pt", label: "Medium (Accurate)" },
    { value: "yolo11l.pt", label: "Large (Most Accurate)" },
];